[build]
  publish = "."
  
[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200
  
[[redirects]]
  from = "/api/*"
  to = "https://kikker-backend.herokuapp.com/api/:splat"
  status = 200
  
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[context.production.environment]
  BACKEND_URL = "https://kikker-backend.herokuapp.com"